= Terrence Tan - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: DiveLog

---

== Overview
The DiveLog application is a Java-based desktop application that is used as a dive log for divers to track their dives. The DiveLog provides a simple way for divers to input details of their dives such as the duration they spent at a particular depth and location of their dives. The application will help to calculate the pressure group that their body is in right now, so that they are more aware of themselves and plan their future dives sessions safely.

//can put as footnote
The pressure group, or a dive profile is a description of a diver's pressure exposure over time. The intended dive profile is useful as a planning tool as an indication of the risks of decompression sickness and oxygen toxicity for the exposure, and also for estimating the volume of open-circuit breathing gas needed for a planned dive, as these depend in part upon the depth and duration of the dive.

//or:
//This document (PPP) is done to showcase my ability to work in a team, my project contributions and ability to perform continuous integration via git.
This project is undertaken as part of the CS2101 and CS2113T twinned modules in NUS as part of our undergraduate degree requirement. The DiveLog is implemented by morphing a the provided addressbook-level4 project.

== Summary of contributions
//highlights:
//talks about the technical challenge that we learnt in order to implement this
//"We considered of how we it could make it more user friendly by looking at it from the user's POV, the colour will be a fast way for user to see the risk level."
* *Major enhancement*: added *the ability to undo/redo previous commands*
** What it does: allows the user to undo all previous commands one at a time. Preceding undo commands can be reversed by using the redo command.
** Justification: This feature improves the product significantly because a user can make mistakes in commands and the app should provide a convenient way to rectify them.
** Highlights: This enhancement affects existing commands and commands to be added in future. It required an in-depth analysis of design alternatives. The implementation too was challenging as it required changes to existing commands.
** Credits: _{mention here if you reused any code/ideas from elsewhere or if a third-party library is heavily used in the feature so that a reader can make a more accurate judgement of how much effort went into the feature}_

* *Minor enhancement*: added a history command that allows the user to navigate to previous commands using up/down keys.

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed releases `v1.3` - `v1.5rc` (3 releases) on GitHub
** Enhancements to existing features:
*** Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
*** Wrote additional tests for existing features to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide: https://github.com[#14]
** Community:
*** PRs reviewed (with non-trivial review comments): https://github.com[#12], https://github.com[#32], https://github.com[#19], https://github.com[#42]
*** Contributed to forum discussions (examples:  https://github.com[1], https://github.com[2], https://github.com[3], https://github.com[4])
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
*** Some parts of the history feature I added was adopted by several other class mates (https://github.com[1], https://github.com[2])
** Tools:
*** Integrated a third party library (Natty) to the project (https://github.com[#42])
*** Integrated a new Github plugin (CircleCI) to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide

//"the below shows my ability to write the guide for the UG"
|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===



== Contributions to the Developer Guide

//A short description of the function
//how the system works
//how the parts work
//if relavent -> how it would work when user does something
//if graphics and text are easily identifable
|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===




== PROJECT: PowerPointLabs

---

_{Optionally, you may include other projects in your portfolio.}_
